# Generated by Django 4.0.2 on 2022-02-21 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_zipxode_customer_zipcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(max_length=200),
        ),
    ]
