# Generated by Django 4.0.2 on 2022-02-21 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_customer_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mobilenumber',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
    ]
