# Generated by Django 4.0.3 on 2022-04-06 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_productreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
